spring.application.name=ShiftKrew
spring.datasource.url=jdbc:postgresql://shiftkrew.ctuug0y2odtq.eu-north-1.rds.amazonaws.com:5432/shiftkrew?sslmode=verify-full&sslrootcert=./global-bundle.pem
spring.datasource.username=postgres
spring.datasource.password=k0l01qaz!QAZ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.maximumPoolSize=20
ref.no.length=16
path.uploads.farmer_templates=C:\\jcodes\\dev\\autographsourcefiles
data.source.file.destination.path=C:\\jcodes\\dev\\autographsourcefiles
security.jwt.secret-key=zWlJQ0w3c2Z6b1pYdVZlQm5xZ0JvZ2Z2R0dQeG9qS2xVQ0R1c1R6c1hWbQ==
security.jwt.expiration-time=86400000
request.connect-timeout=60000
token.issuer.url=http://localhost:8080
token.issuer.x509=C:\\jcodes\\dev\\keys\\smartbanking\\token-issuer-x509.txt
token.issuer.pkcs12=C:\\jcodes\\dev\\keys\\smartbanking\\token-issuer-pkcs.p12
token.period.in.mins=1440
token.otp.period.in.mins=5

service.provider.pkcs=C:\\jcodes\\dev\\keys\\smartbanking\\service-provider-pkcs.p12
service.provider.x509=C:\\jcodes\\dev\\keys\\smartbanking\\service-provider-x509.txt
path.uploads.user.profile.picture=C:\\jcodes\\dev\\keys\\smartbanking\\fileuploads\\id-documents
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force-response=true
request.read-timeout=60000
authentication.provider.url=http://137.184.47.182:8081/token-issuer-1.0.0/api/authenticate

jwt.token.validity=18000
jwt.signing.key=cnFZxXsm4lkm2mH++Q1eC0MKZh3xQuvGJrpqtMf0u8MTQcNYi0yYsl/GcOVS72o3ieSk4RnlK+4M1hvh4t+gcg==
jwt.authorities.key=roles
jwt.token.prefix=Bearer
jwt.header.string=Authorization

holiday.pay.percentage=12.07
insurance.pension.percentage=11
shift.krew.vat.percentage=20
shift.krew.charge.percentage=5
pay.to.bank.account.id=1
